name: Renovate
on:
  workflow_dispatch:

  schedule:
    - cron: '0 5,7 * * *'

permissions:
  contents: read

jobs:
  renovate:
    uses: qubesome/.github/.github/workflows/renovate.yml@main
    secrets:
      RENOVATE_PRIVATE_KEY: ${{ secrets.RENOVATE_PRIVATE_KEY }}
      RENOVATE_APP_ID: ${{ secrets.RENOVATE_APP_ID }}
